version: "3"

services:
  web:
    build: .
    command: gunicorn project.wsgi --bind 0.0.0.0:8001
    networks:
      - backend
    depends_on:
      - db

  nginx:
    image: nginx:latest
    networks:
      - backend
    depends_on:
      - web

  db:
    image: postgres:13
    networks:
      - backend

  # redis:
  #   image: redis:6-alpine
  #   networks:
  #     - backend
  #
  # celery:
  #   build: .
  #   command: celery -A project worker -l info
  #   networks:
  #     - backend
  #   depends_on:
  #     - redis
  #     - db
  #
  # celery-beat:
  #   build: .
  #   command: celery -A project beat -l info
  #   networks:
  #     - backend
  #   depends_on:
  #     - redis

networks:
  backend:
    driver: bridge
