version: "3"

services:
  web:
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ./django:/code
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG:-False}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DB_HOST: "db"
      DJANGO_WEB_HOST: "web"
      DJANGO_DB_NAME: ${DJANGO_DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

  nginx:
    restart: unless-stopped
    ports:
      - 8088:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./django/static:/code/static

  db:
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

  db-admin:
    restart: unless-stopped
    image: dpage/pgadmin4
    volumes:
      - ./pgadmin-conf:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - backend
