version: "3"

services:
  web:
    restart: unless-stopped
    ports:
      - 8001:8001
    volumes:
      - ./django:/code
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG:-False}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_WEB_HOST: ${DJANGO_WEB_HOST}
      DJANGO_DB_HOST: "db"
      DJANGO_DB_NAME: ${DJANGO_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  nginx:
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${SSL_CERTIFICATE}:/etc/nginx/certs/certificate.crt
      - ${SSL_CERTIFICATE_KEY}:/etc/nginx/certs/key.key
      - ./django/static:/code/static
    depends_on:
      - db-admin

  db:
    restart: unless-stopped
    # ports:
    #   - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DJANGO_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  db-admin:
    restart: unless-stopped
    image: dpage/pgadmin4:latest
    # volumes:
    #   - ./pgadmin-conf:/var/lib/pgadmin
      # create and run `sudo chown -R 5050:5050 pgadmin-conf` beforehand
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    networks:
      - backend

  # redis:
  #   restart: unless-stopped
  #
  # celery:
  #   restart: unless-stopped
  #   volumes:
  #     - ./django:/code
  #   environment:
  #     DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
  #     DJANGO_DB_NAME: ${DJANGO_DB_NAME}
  #     DJANGO_DB_HOST: "db"
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #
  # celery-beat:
  #   restart: unless-stopped
  #   volumes:
  #     - ./django:/code
  #   environment:
  #     DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
  #     DJANGO_DB_NAME: ${DJANGO_DB_NAME}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
